# Generated by Django 2.1.4 on 2019-03-21 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='power_test',
            field=models.CharField(choices=[('Yes', 'Pass.'), ('No', 'Fail.')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='starter',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
