# Generated by Django 2.1.5 on 2019-03-08 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190130_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='item',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluation_stage',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_of_item',
        ),
        migrations.AddField(
            model_name='donor',
            name='invoicenum',
            field=models.CharField(default='2019010100', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoicenum',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('HardDrive', 'HardDrive')], max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Dell', 'Dell'), ('HP', 'HP'), ('MicroSoft', 'MicroSoft'), ('Lenovo', 'Lenovo'), ('Google', 'Google')], max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='warehousenum',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
