# Generated by Django 2.1.5 on 2019-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190308_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='number_of_donations',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_phone',
            field=models.IntegerField(max_length=100),
        ),
    ]
