# Generated by Django 2.1.5 on 2019-04-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190405_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice_nbr',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='boards.Donor'),
        ),
    ]
