# Generated by Django 2.1.5 on 2019-04-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190405_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='invoice_nbr',
        ),
    ]
