# Generated by Django 2.1.5 on 2019-04-05 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20190405_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to=settings.AUTH_USER_MODEL),
        ),
    ]
