# Generated by Django 2.1.5 on 2019-04-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190405_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='starter',
        ),
    ]
