# Generated by Django 2.1.5 on 2019-04-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_remove_type_starter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='warehouse_nbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='boards.Item'),
        ),
    ]
