# Generated by Django 2.1.5 on 2019-04-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20190405_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='warehouse_nbr',
        ),
    ]
