# Generated by Django 2.1.5 on 2019-04-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_remove_type_warehouse_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='invoice_nbr',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='boards.Donor'),
        ),
    ]
