# Generated by Django 2.1.4 on 2019-03-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='comments',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='media_erasure',
            name='complete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='media_erasure',
            name='item_nbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meadia_erasure', to='boards.Item'),
        ),
        migrations.AlterField(
            model_name='quality_assessment',
            name='comments',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
